# Generated by Django 2.0.7 on 2018-07-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='certification',
            field=models.ForeignKey(default='63cf7a373c134e239edcf43a769f80e5', on_delete=False, to='app.Certification'),
            preserve_default=False,
        ),
    ]
