# Generated by Django 2.0.7 on 2018-07-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_current_certification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Current',
            new_name='Account',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
    ]
