# Generated by Django 2.0.7 on 2018-07-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_biz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biz',
            name='order_id',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
