# Generated by Django 2.0.7 on 2018-07-31 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180731_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingStrategy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=18, default=0, max_digits=40)),
                ('rule', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=18, default=0, max_digits=40)),
                ('total', models.DecimalField(decimal_places=18, default=0, max_digits=40)),
                ('interval', models.DecimalField(decimal_places=18, default=0, max_digits=40)),
                ('enable', models.BooleanField(default=False)),
                ('side', models.ForeignKey(on_delete=False, to='app.OrderSide')),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
            },
        ),
    ]
