# Generated by Django 2.0.7 on 2018-07-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tradingstrategy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingstrategy',
            old_name='side',
            new_name='order_side',
        ),
    ]
