# Generated by Django 2.0.7 on 2018-07-31 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180731_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradingstrategy',
            options={'verbose_name': 'TradingStrategy', 'verbose_name_plural': 'TradingStrategys'},
        ),
    ]
