# Generated by Django 2.0.7 on 2018-07-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180731_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingstrategy',
            name='username',
            field=models.CharField(default='admin', max_length=64),
            preserve_default=False,
        ),
    ]
