# Generated by Django 2.0.7 on 2018-08-01 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tradingstrategy_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('currency', 'category')},
        ),
    ]
