# Generated by Django 2.0.7 on 2018-08-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180801_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderside',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordertype',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
