# Generated by Django 2.0.7 on 2018-08-01 03:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180801_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'OrderRule',
                'verbose_name_plural': 'OrderRules',
            },
        ),
    ]
